.TH "mate-keyring" "1" 
.SH "NAME" 
mate-keyring \(em  interact with the mate-keyring-daemon
.SH "SYNOPSIS" 
.PP 
\fBmate-keyring\fR [\fB\-\-help \fP] [\fBcommand \fP] [\fBoptions \fP]
.SH "DESCRIPTION" 
.PP 
\fBmate-keyring\fR allows for some command line control of the
mate-keyring-daemon.
.SH "OPTIONS" 
.IP "\fB\-\-help\fP" 10 
Display help 
.IP "\fBcertificate-exception\fP" 10 
provide a certificate exception
.IP "\fBimport\fP" 10 
import a certificate
.IP "\fBversion\fP" 10 
print the version.
.SH "BUGS"
If you find bugs in the \fBmate-keyring\fP program, please report them on:
https://github.com/mate-desktop/mate-keyring/issues
